# Generated by Django 4.2.1 on 2023-05-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gadgets',
            options={'verbose_name': 'Gadget', 'verbose_name_plural': 'Gadgets'},
        ),
    ]
